DROP TABLE IF EXISTS category CASCADE;
CREATE TABLE category(
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS brand CASCADE;
CREATE TABLE brand(
    brand_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS product CASCADE;
CREATE TABLE product(
    product_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    brand_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    stock INT NOT NULL
);

DROP TABLE IF EXISTS member CASCADE;
CREATE TABLE member(
    member_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(1024) NOT NULL
);